// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cwe1z_GTNIS09RDOrKKsa5F7S60lnC8',
    appId: '1:613830086557:web:6e9222c99be52abad9a974',
    messagingSenderId: '613830086557',
    projectId: 'wallflower-48313',
    authDomain: 'wallflower-48313.firebaseapp.com',
    storageBucket: 'wallflower-48313.appspot.com',
    measurementId: 'G-YVEYWWT9FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_M9sPmxR9eAa_hfYDcPzDlxXL0PZrnrk',
    appId: '1:613830086557:android:c792a7121383a1c7d9a974',
    messagingSenderId: '613830086557',
    projectId: 'wallflower-48313',
    storageBucket: 'wallflower-48313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLq62-x6iRrlJOhKC66fnTt1FJ5gjpo-8',
    appId: '1:613830086557:ios:747e0077234cfd03d9a974',
    messagingSenderId: '613830086557',
    projectId: 'wallflower-48313',
    storageBucket: 'wallflower-48313.appspot.com',
    iosClientId: '613830086557-e1buhj2dntit5l17kbg4o0rgpih93egh.apps.googleusercontent.com',
    iosBundleId: 'com.asmit.nitpSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLq62-x6iRrlJOhKC66fnTt1FJ5gjpo-8',
    appId: '1:613830086557:ios:747e0077234cfd03d9a974',
    messagingSenderId: '613830086557',
    projectId: 'wallflower-48313',
    storageBucket: 'wallflower-48313.appspot.com',
    iosClientId: '613830086557-e1buhj2dntit5l17kbg4o0rgpih93egh.apps.googleusercontent.com',
    iosBundleId: 'com.asmit.nitpSocial',
  );
}
